### PR TITLE
Spanish prosilver images

### PR DESCRIPTION
**Pull request by phpbb-es**
Spanish prosilver images, this images are "valid" for others themes/styles. ;)

### CODE REVIEW

**Comment by lavigor** [comment]
[Errors](https://travis-ci.org/Tatiana5/profile_side_switcher/jobs/107617852#L757) in ICC sniffer.
Please fix it so that I can submit it to the CDB very soon. ;-)

**Comment by phpbb-es** [comment]
The image is not correct?

icon_user_online_left

This is edited PSD again

**Comment by lavigor** [comment]
I think it just needs to be re-saved with ICC profile.
Personally I do not know the issues that it can cause, but if it can be fixed, it should be fixed. =)
Galixte fixed his images, I think that this image should be fixed too.

**Comment by lavigor** [comment]
Finally deleted ICC profile and Travis build passed.
Spanish translation was included in the package and submitted to the CDB.
Thanks again.

**Comment by phpbb-es** [comment]
Thanks @lavigor ;)

**Pull request merged**
