### PR TITLE
Add more styles

### PR DESCRIPTION
**Pull request by Galixte**
- Activate or disable support for 23 styles:
 - Aqua-Marine,
 - FTH_Tropic ; disabled because the mini-profile is already on left side,
 - iCGstation,
 - pbtech ; disabled because the mini-profile is already on left side,
 - pbwow3 and 12 child styles ; disabled because the mini-profile is already on left side,
 - proFormell,
 - prOrange-Black ; add EN & FR images icon_online_left,
 - prosilver,
 - prosilver Flat,
 - prosilver Special Edition,
 - We_universal ; disabled because the mini-profile is already on left side.

- Add PSD file to cutomize the icon_user_online_left file for other languages.

### CODE REVIEW

**Comment by Tatiana5** [comment]
It doesn't need switching off еру default profile-on-the-left setting.

**Comment by Galixte** [comment]
Hi @Tatiana5,

by default on phpBB the mini-profile is on right. Why to set on left for guests ?

Leave the choice for registered users it’s a good way.

That why it’s the only modification that i found to set the mini-profile on right like by default on phpBB.

**Comment by lavigor** [comment]
@Galixte, yes, there's a way.
You can change the setting manually in the ACP for Anonymous so that guests will see miniprofiles rightsided.
Please do not change the default setting (I personally like seeing miniprofiles always on the left side, it is typical for many boards).
We can add the instructions for changing the setting for guests though.

**Comment by lavigor** [comment]
Also please check out the travis errors about stripped ICC profile in some images.

**Comment by Galixte** [comment]
Who is the developer  Tatiana5 or you ?

“You can change the setting manually in the ACP for Anonymous so that guests will see miniprofiles rightsided.”
I already test this way and It doesn’t work. That’s why i have search an other way: https://github.com/Tatiana5/profile_side_switcher/pull/13/files#diff-16d7c311f6f85d3e2e62faa6a51965a0.

“Please do not change the default setting (I personally like seeing miniprofiles always on the left side, it is typical for many boards).”
I don’t talking about other boards, but phpBB. For phpBB users the default is on the right side. If an admin adds this functionality it’s not for all board users, the goal is to leave the choice, not to force, especially guests.

“We can add the instructions for changing the setting for guests though.”
Yes it will be welcome.

“Also please check out Travis errors about stripped ICC profile in some images.”

I see those results:
```
Test results for extension:
Warning: Can't detect the file type for prosilver_icon_user_online_left.zip, handling it as a binary file.
Warning: Can't detect the file type for phpunit.xml.dist, handling it as a binary file.
Error: Packaging structure doesn't meet the extension DB policies.
```
Would you that i delete the ZIP file ?
The phpunit.xml.dist file wasn’t added by me.

**Comment by Tatiana5** [comment]
<blockquote>Who is the developer Tatiana5 or you ?</blockquote>
LavIgor and I are on the same team

**Comment by lavigor** [comment]
I was talking about other lines: https://travis-ci.org/Tatiana5/profile_side_switcher/jobs/70491110#L751.
However, I don't think that it is a serious problem.

> For phpBB users the default is on the right side.

That is why this extension was created I think. Because most boards (and not only boards) for LTR languages, especially Russian, have miniprofiles on the left side. Just because it looks better for LTR languages.

> I already test this way and It doesn’t work.

OK. Wait for my PR. But please leave the default setting as it is now.
@Tatiana5, what do you think?

**Comment by Tatiana5** [comment]
@lavigor , I think so too

**Comment by lavigor** [comment]
@Galixte, please test the latest version.
Now you can change the profile side for guests in the ACP.

**Comment by Galixte** [comment]
Ok thanks, could you merge this now, i removed those that you want.

**Comment by Galixte** [comment]
For ICC, maybe this will be useful: https://github.com/VSEphpbb/dbtool/commit/b30d42a6cda5811353849d7458e4423c14996c0c

**Comment by Galixte** [comment]
On last thing is missing, to determine the default parameter for profile side, allow to set by default for new registered user if it on left or on right.

Could you add this option, please ?

**Pull request merged**
