### PR TITLE
Allow changing the profile side when JavaScript is off.

### PR DESCRIPTION
**Pull request by lavigor**
Plus some other fixes.

### CODE REVIEW

**Comment by lavigor** [comment]
Hmm... Maybe the whole extension should be adapted for that case.
I can do that if you want.

**Comment by dragosvr92** [comment]
lavigor, does your patch fix this issue?
https://github.com/Tatiana5/profile_side_switcher/issues/7
If not, do you think you could patch it? This extensions is great, but tatiana does not seem to have time for it, as its not even on phpbb yet. Dont think she would mind.

**Comment by lavigor** [comment]
> does your patch fix this issue?
No. I think that you're talking about an issue with language. This PR I'd not a patch for it.

> If not, do you think you could patch it?
I can try to fix it later.

**Comment by Tatiana5** [comment]
@lavigor, thanks

**Comment by dragosvr92** [comment]
Thanks lavigor, can you please reply here when you found a fix? :)

**Comment by lavigor** [comment]
I've already created a fix. =)

**Comment by dragosvr92** [comment]
Thank you lavigor. You've done a good job on this extension :)
Dont suppose i could bother you for a version check too? 
The main author seems too busy to even leave a reply as far as i can see.

**Comment by lavigor** [comment]
> Dont suppose i could bother you for a version check too?
I thought about that.
But only Tatiana can create a new branch for version check feature (otherwise I can do it in my fork, but this is not the right way).

**Comment by dragosvr92** [comment]
Yeah, well this is an intensely used extension and it is a good one ! 
She did a really good job on it. But as it is a very used extension, it needs the author to have enough time to be dedicated to it and fix bugs for new versions and ensure it always functions right. 

Seeing how tatiana seems to be very busy to continue support for this, i think it would be good idea for you two to work together on it. I think you deserve that considering how helpful you were. 

And this should really be posted over phpbb. :D

**Comment by lavigor** [comment]
> it would be good idea for you two to work together on it

I don't mind about that.
I'm currently working on Upload Extensions, but can maintain some other extensions as well.

**Pull request merged**
